### PR TITLE
Various improvements

### LINKED ISSUE #1: work around %s
%s gets translated to a space, and there is no way to escape %s... so we must encode % as keycode, or split the string there, when it precedes s.

https://android.googlesource.com/platform/frameworks/base/+/android-4.4.2_r1/cmds/input/src/com/android/commands/input/Input.java#159

### PR DESCRIPTION
**Pull request by matthijskooijman**
I had previously implemented reading from stdin (as I suggested in #6), but I just noticed I never submitted that improvement. I just went ahead and also implemented my other suggestion from #6 (using `subprocess.call` rather than `os.system`) and also fixed #1 allowing `%s` to be sent.

All this was tested with ADB 8.1.0 on a Fairphone 2 running Android 7.1.2.

### CODE REVIEW

**Comment by matthijskooijman** [comment]
Note that this also includes your fix for #6 that you previously did, but not merged to master yet.

**Comment by matthijskooijman** [comment]
Also note that this removes `--fast`, but re-reading your comment on #6 you might not have intended to remove it but just did not get around to re-implementing that. If so, re-implementing it could be a matter of changing the %-splitting regex to something like (untested):

    for part in re.findall('[^%]{1,7}%?', string):

**Comment by koroshiya** [comment]
Looks good to me. I've given this a quick test on a Linux machine and everything appears to work as intended.

**Comment by gcb** [comment]
This will probably break on windows (by implying --fast and not breaking on spaces), but I don't think anyone is forced to use windows' CMD today as I was when I started this, so :+1:

Anyone still stuck to windows should be using something like git-shell or cygwin or even a VM.

**Pull request merged**
